config/routes.rb
Rails.application.routes.draw do
  resources :watchlist, only: %i[index create destroy]

  devise_for :users, controllers: { registrations: 'registrations' }

  resources :reviews, except: %i[show new create]

  resources :users, only: %i[show] do
    resources :reviews, only: %i[create new]
  end

  resources :bookings, except: %i[new create show]

  # Defines the resourceful routes for the listings controller
  resources :listings do
    resources :bookings, only: %i[new create]
  end

  # Defines the root path route ("/")
  root 'listings#index'
end

app/models/listing.rb
class Listing < ApplicationRecord
  belongs_to :tutor, class_name: 'User', foreign_key: 'tutor_id'
  has_and_belongs_to_many :saved_by_users, class_name: 'User', join_table: 'listings_users'
  has_and_belongs_to_many :subjects
  has_many :bookings, dependent: :destroy

  validates :tutor, :title, :content, :subjects, presence: true

  # returns boolean true if the listing is already saved
  def already_saved?(user)
    user.saved_listings.include?(self)
  end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]
  before_action :check_auth
  before_action :set_listing, only: %i[show update destroy edit]
  before_action :set_listing_subjects, only: %i[update create]

  # Sets a list of listings renders the listing index view.
  def index
    @listings = Listing.all
  end

  # Renders the show listing view
  def show; end

  # Creates and sets a new instance of listing.
  def new
    @listing = Listing.new
  end

  # Validates the params fields and saves a new listing if it passes validation
  # else renders the new form with relevent error alert.
  def create
    create_validator(@listing, @listing)
  end

  # Renders the edit Listing form
  def edit; end

  # Attempts to update the Listing and if it passes validation it will render the @listing,
  # else, it will redirect to root_path with relevent error alert
  def update
    if (current_user != @listing.tutor) || (current_user.present? == false)
      flash[:notice] = 'Access Denied'
      return redirect_to(:root)
    end

    update_validator(@listing, listing_params, @listing)
  end

  # Attempts to destroy the record if the user is tied to the listing and
  # present otherwise it will redirect to the root path with the relevent error alert.
  def destroy
    if (current_user != @listing.tutor) || (current_user.present? == false)
      flash[:notice] = 'Access Denied'
      return redirect_to(:root)
    end

    @listing.destroy
    redirect_to listings_path
  end

  private

  # Sets the authorisation policies to be used as a before action
  def check_auth
    authorize Listing
  end

  # Sets the listing subjects for the listing resource
  def set_listing_subjects
    @listing = Listing.new(tutor: current_user, **listing_params)
    subject = params[:listing][:subjects]
    @listing.subjects << Subject.find_by(name: subject)
  end

  # returns the listing strong parameters defined in the route request
  def listing_params
    params.require(:listing).permit(:title, :content)
  end

  # Sets the listing resource based on the listing id
  def set_listing
    @listing = Listing.find(params[:id])
  end
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/listings/_form.html.erb
<%= form_with(model: @listing, data: {turbo: false}) do |f| %>
  <fieldset class="mb-3 d-flex flex-column col-3">
    <%= f.label "Subjects"%>
    <%= f.select :subjects, Subject.pluck(:name) %>
  </fieldset>
  <fieldset class="mb-3 d-flex flex-column">
    <%= f.label "Title" %>
    <%= f.text_field :title %>
  </fieldset>
  <fieldset class="mb-3 d-flex flex-column">
    <%= f.label "Content" %>
    <%= f.text_area :content, class: "" %>
  </fieldset>
  <fieldset>
    <%= f.submit class: 'btn btn-primary' %>
  </fieldset>
<% end %>

app/views/listings/edit.html.erb
<section>
  <div class="container">
    <div class="row justify-content-center">
      <div  class="col-6">
        <h5 class="d-inline-block">Edit Listing:</h5>
      </div>
    </div>
    <div class="row justify-content-center">
      <div class="col-6">
        <%= render 'form' %>
      </div>
    </div>
  </div>
</section>

app/views/listings/index.html.erb
<section class="container">
  <div class="row">
    <% @listings.each do |listing| %>
      <div class="col-12 col-md-4 col-lg-3 py-2">
        <div class="card border-0">
          <div class="card-body d-flex flex-column align-items-center">
            <% if current_user && listing.already_saved?(current_user) %>
              <div class="position-relative w-100 d-flex justify-content-end">
                <div class="position-absolute h-100 opacity-0">
                  <%= button_to('', watchlist_path(listing.id), class: 'w-100 h-100 position-absolute end-0', method: :delete) %>
                </div>
                <svg xmlns="http://www.w3.org/2000/svg" aria-hidden="true" role="img" width="1em" height="1em" preserveAspectRatio="xMidYMid meet" viewBox="0 0 24 24"><path fill="blue" d="M12 9a3 3 0 0 0-3 3a3 3 0 0 0 3 3a3 3 0 0 0 3-3a3 3 0 0 0-3-3m0 8a5 5 0 0 1-5-5a5 5 0 0 1 5-5a5 5 0 0 1 5 5a5 5 0 0 1-5 5m0-12.5C7 4.5 2.73 7.61 1 12c1.73 4.39 6 7.5 11 7.5s9.27-3.11 11-7.5c-1.73-4.39-6-7.5-11-7.5Z"/></svg>
              </div>
            <% elsif current_user %>
              <div class="position-relative w-100 d-flex justify-content-end">
                <div class="position-absolute h-100 opacity-0">
                  <%= button_to('', watchlist_index_path(id: listing.id), class: 'w-100 h-100 position-absolute end-0', method: :post) %>
                </div>
                <svg xmlns="http://www.w3.org/2000/svg" aria-hidden="true" role="img" width="1em" height="1em" preserveAspectRatio="xMidYMid meet" viewBox="0 0 24 24"><path fill="currentColor" d="M12 4.5C7 4.5 2.73 7.61 1 12c1.73 4.39 6 7.5 11 7.5c.36 0 .72 0 1.08-.05a6.09 6.09 0 0 1-.08-.95c0-.56.08-1.12.24-1.66c-.41.1-.82.16-1.24.16a5 5 0 0 1-5-5a5 5 0 0 1 5-5a5 5 0 0 1 5 5c0 .29-.03.59-.08.88c.66-.25 1.37-.38 2.08-.38c1.17 0 2.31.34 3.29 1c.27-.5.51-1 .71-1.5c-1.73-4.39-6-7.5-11-7.5M12 9a3 3 0 0 0-3 3a3 3 0 0 0 3 3a3 3 0 0 0 3-3a3 3 0 0 0-3-3m6 5.5v3h-3v2h3v3h2v-3h3v-2h-3v-3h-2Z"/></svg>
              </div>
            <% end %>
            <% if listing.tutor.profile_picture.attached? %>
              <%= cl_image_tag listing.tutor.profile_picture.key, class: 'rounded-circle', crop: :fill, height: 100, aspect_ratio: '1:1', cloud_name: 'dakvf2jcu' %>
            <% else %>
                  <svg xmlns="http://www.w3.org/2000/svg" aria-hidden="true" role="img" width="auto" height="100" preserveAspectRatio="xMidYMid meet" viewBox="0 0 24 24"><path fill="currentColor" d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10s10-4.48 10-10S17.52 2 12 2zm0 4c1.93 0 3.5 1.57 3.5 3.5S13.93 13 12 13s-3.5-1.57-3.5-3.5S10.07 6 12 6zm0 14c-2.03 0-4.43-.82-6.14-2.88a9.947 9.947 0 0 1 12.28 0C16.43 19.18 14.03 20 12 20z"/></svg>
            <% end %>
            <h5 class="card-title pt-3"> <%= listing.title %></h5>
            <p class="card-text text-center"> <%= truncate(listing.content, length: 125, omission: '...') %></p>
            <%= button_to('Show Listing', listing, class: 'btn btn-primary', method: :get) %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</section>

app/views/listings/new.html.erb
<section>
  <div class="container">
    <div class="row justify-content-center">
      <div  class="col-6">
        <h5 class="d-inline-block">Create Listing:</h5>
      </div>
    </div>
    <div class="row justify-content-center">
      <div class="col-6">
        <%= render 'form' %>
      </div>
    </div>
  </div>
</section>

app/views/listings/show.html.erb
<section>
  <div class="container">
    <div class="row justify-content-center">
      <div class="d-flex justify-content-center">
        <% if @listing.tutor.profile_picture.attached? %>
          <%= cl_image_tag @listing.tutor.profile_picture.key, class: 'rounded-circle', crop: :fill, height: 100, aspect_ratio: '1:1', cloud_name: 'dakvf2jcu' %>
        <% else %>
          <svg xmlns="http://www.w3.org/2000/svg" aria-hidden="true" role="img" width="" height="100" preserveAspectRatio="xMidYMid meet" viewBox="0 0 24 24"><path fill="currentColor" d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10s10-4.48 10-10S17.52 2 12 2zm0 4c1.93 0 3.5 1.57 3.5 3.5S13.93 13 12 13s-3.5-1.57-3.5-3.5S10.07 6 12 6zm0 14c-2.03 0-4.43-.82-6.14-2.88a9.947 9.947 0 0 1 12.28 0C16.43 19.18 14.03 20 12 20z"/></svg>
        <% end %>
      </div>
    </div>
    <div class="row justify-content-center">
      <div class="d-flex justify-content-center">
        <h1> <%= @listing.title %> </h1>
      </div>
    </div>
    <div class="row justify-content-center">
      <div class="d-flex justify-content-center">
        <h2> (<%= @listing.subjects.first.name %>) </h2>
      </div>
    </div>
    <div class="row justify-content-center">
      <div class="d-flex justify-content-center">
        <div class="w-50 d-flex justify-content-center">
          <p> <%= @listing.content %> </p>
        </div>
      </div>
    </div>
    <div class="row justify-content-center">
      <div class="d-flex justify-content-center">
        <% if user_signed_in? %>
          <% if @listing.tutor != current_user %>
            <% if current_user.has_role?(:student) %>
              <%= button_to('+ Booking', new_listing_booking_path(@listing), class: 'btn btn-outline-dark m-3', method: :get) %>
            <% end %>
            <%= button_to('View Tutor', user_path(@listing.tutor), class: 'btn btn-outline-dark m-3', method: :get) %>
          <% else %>
            <%= button_to('Edit', edit_listing_path(@listing.id), class: 'btn btn-outline-dark m-3', method: :get)%>
            <%= button_to('Delete', listing_path(@listing.id), class: 'btn btn-outline-dark m-3', method: :delete, form: { data: { turbo_confirm: "Are you sure you want to delete your listing? " } }) %>
          <% end %>
        <% end %>
      </div>
    </div>
    <div class="row justify-content-center">
      <div class="d-flex justify-content-center">
        <p class="text-muted"> Listed: <%= @listing.created_at %> </p>
      </div>
    </div>
  </div>
</div>
</section>