config/routes.rb
Rails.application.routes.draw do
  resources :watchlist, only: %i[index create destroy]

  devise_for :users, controllers: { registrations: 'registrations' }

  resources :reviews, except: %i[show new create]

  resources :users, only: %i[show] do
    resources :reviews, only: %i[create new]
  end

  resources :bookings, except: %i[new create show]

  # Defines the resourceful routes for the listings controller
  resources :listings do
    resources :bookings, only: %i[new create]
  end

  # Defines the root path route ("/")
  root 'listings#index'
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :student, class_name: 'User', foreign_key: 'student_id'
  belongs_to :listing

  has_one :tutor, through: :listing

  validates :student, presence: { message: 'must be signed in' }
  validates :start, presence: true
  validates :finish, comparison: { greater_than: :start }
  validate :booking_cannot_be_at_same_time_as_another_booking,
           :start_cannot_be_in_the_past, :user_must_be_student

  # Returns boolean true if a Booking is in the future
  def self.in_future
    where('start > :start', start: Time.zone.now.to_datetime)
  end

  # returns and adds an error if the user is not a student
  def user_must_be_student
    return if !start || !finish || student.has_role?(:student)

    errors.add(:student, 'must have student role. To change roles see Account')
  end

  # returns and adds an error if the booking is at the same time as another booking
  def booking_cannot_be_at_same_time_as_another_booking
    return if !start || !finish

    tutor_bookings = listing.tutor.bookings_as_tutor
    bookings = tutor_bookings.where(start: (start..finish))
                             .or(tutor_bookings.where(finish: (start..finish)))
                             .or(tutor_bookings.where('start < :start AND finish > :finish', start: start,
                                                                                             finish: finish))

    return if (tutor_bookings.length == 1 && tutor_bookings.first != self) || bookings.empty?

    errors.add :base, :invalid,
               message: "There is already another booking at #{bookings.first.start} to #{bookings.first.finish}"
  end

  # returns and adds an error if the booking is in the past.
  def start_cannot_be_in_the_past
    errors.add(:start, "can't be in the past") if start.present? && start < Time.zone.now.to_datetime
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: %i[update destroy edit]
  before_action :set_listing, only: %i[new create]
  before_action :authenticate_user!
  before_action :check_auth

  # Sets a list of bookings that occur in the future sorted by the start date and renders the Bookings index view.
  def index
    @all_bookings = []
    current_user.bookings_as_tutor.in_future.each do |booking|
      @all_bookings << booking
    end
    current_user.bookings_as_student.in_future.each do |booking|
      @all_bookings << booking
    end
    @all_bookings.sort_by!(&:start)
  end

  # Creates and sets a new instance of Booking.
  def new
    @booking = Booking.new
  end

  # Validates the params fields and saves a new booking and render the bookings_path if it
  # passes validation else renders the new form with relevent error alert.
  def create
    @booking = Booking.new(student: current_user, listing: @listing, **booking_params)
    create_validator(@booking, bookings_path)
  end

  # Renders the edit booking form
  def edit; end

  # Attempts to update the Booking and if it passes validation it will render the bookings_path,
  # else, it will redirect to root_path with relevent error alert
  def update
    if ((current_user != @booking.tutor) && (current_user != @booking.student)) || (current_user.present? == false)
      flash[:notice] = 'Access Denied'
      return redirect_to(:root)
    end
    update_validator(@booking, booking_params, bookings_path)
  end

  # Attempts to destroy the record if the user is tied to the booking and
  # present otherwise it will redirect to the root path with the relevent error alert.
  def destroy
    if ((current_user != @booking.tutor) && (current_user != @booking.student)) || (current_user.present? == false)
      flash[:notice] = 'Access Denied'
      return redirect_to(:root)
    end
    @booking.destroy
    redirect_to bookings_path
  end

  private

  # Sets the authorisation policies to be used as a before action
  def check_auth
    authorize Booking
  end

  # Sets the listing resource based on the listing id
  def set_listing
    @listing = Listing.find(params[:listing_id])
  end

  # Sets the booking resource based on the booking id
  def set_booking
    @booking = Booking.find(params[:id])
  end

  # Returns the strong params for booking based on the route.
  def booking_params
    params.require(:booking).permit(:start, :finish)
  end
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/views/bookings/_form.html.erb
  
<fieldset class="mb-3 d-flex flex-column col-12 col-md-4">
  <%= f.label "Start Time" %>
  <%= f.datetime_field :start %>
</fieldset>
<fieldset class="mb-3 d-flex flex-column col-12 col-md-4">
  <%= f.label "Finish Time" %>
  <%= f.datetime_field :finish %>
</fieldset>
<fieldset>
  <%= f.submit class: 'btn btn-primary' %>
</fieldset>

app/views/bookings/edit.html.erb
<section class="m-3">
  <div class="container">
    <div class="row justify-content-center">
      <div  class="col-md-3">
      </div>
      <div  class="col-6">
        <h5 class="d-inline-block">Edit Booking:</h5>
      </div>
    </div>
    <div class="row justify-content-center">
      <div  class="col-md-3">
      </div>
      <div class="col-6">
        <%= form_with(model: @booking, data: {turbo: false}, method: 'put') do |f| %>
          <%= render partial: 'form', locals: { f: f } %>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/bookings/index.html.erb
<section class="container">
  <div class="row justify-content-center">
    <div  class="col-6 text-center p-5">
      <h1 class="d-inline-block">Bookings:</h1>
    </div>
  </div>
  <div class="row justify-content-center d-none d-md-flex">
    <% col_length = %w[2 3 2 3] %>
    <% %w[Type Timeslot Tutor Email ].each_with_index do |heading, index| %>
      <div  class="col-<%= col_length[index] %>">
        <h2 class="d-inline-block"><%= heading %></h2>
      </div>
    <% end %>
    <div  class="col-2">
    </div>
  </div>
  <% @all_bookings.each do |booking| %>
    <div class="row card bg-light flex-column flex-md-row justify-content-center align-items-center">
      <div  class="col-12 col-md-2">
        <h1 class="d-md-none"> Type </h1>
        <% if booking.tutor == current_user %>
          <p class="d-inline-block"> Teaching </p>
        <% else %>
          <p class="d-inline-block"> studying </p>
        <% end %>
      </div>
      <div  class="col-12 col-md-3">
        <h1 class="d-md-none"> Timeslot </h1>
        <p class="d-inline-block"> <%= booking.start %> to <%= booking.finish %> </p>
      </div>
      <div  class="col-12 col-md-2">
        <h1 class="d-md-none"> Tutor </h1>
        <p class="d-inline-block"> <%= link_to("#{booking.tutor.name}", user_path(booking.tutor.id))%> </p>
      </div>
      <div  class="col-12 col-md-3">
        <% if booking.tutor == current_user %>
          <h1 class="d-md-none"> Email </h1>
          <p class="d-inline-block"> <%= booking.student.email %> </p>
        <% else %>
          <h1 class="d-md-none"> Email </h1>
          <p class="d-inline-block"> <%= booking.tutor.email %> </p>
        <% end %>
      </div>
      <div  class="col-12 col-md-2 d-flex justify-content-md-between">
        <%= link_to('Edit', edit_booking_path(booking), class: 'btn btn-warning m-2 m-md-0') unless booking.tutor == current_user %>
        <%= button_to('Delete', booking, class: 'btn btn-danger m-2 m-md-0', method: :delete, form: { data: { turbo_confirm: "Are you sure you want to delete this booking ?" } })%>
      </div>
    </div>
  <% end %>
</section>

app/views/bookings/new.html.erb
<section class="m-3">
  <div class="container">
    <div class="row justify-content-center">
      <div  class="col-md-3">
      </div>
      <div  class="col-6">
        <h5 class="d-inline-block">New Booking:</h5>
      </div>
    </div>
    <div class="row justify-content-center">
      <div  class="col-md-3">
      </div>
      <div class="col-6">
        <%= form_with(model: @booking, url: [@listing, @booking], data: {turbo: false}) do |f| %>
          <%= render partial: 'form', locals: { f: f } %>
        <% end %>
      </div>
    </div>
  </div>
</section>