config/routes.rb
Rails.application.routes.draw do
  resources :watchlist, only: %i[index create destroy]

  devise_for :users, controllers: { registrations: 'registrations' }

  resources :reviews, except: %i[show new create]

  resources :users, only: %i[show] do
    resources :reviews, only: %i[create new]
  end

  resources :bookings, except: %i[new create show]

  # Defines the resourceful routes for the listings controller
  resources :listings do
    resources :bookings, only: %i[new create]
  end

  # Defines the root path route ("/")
  root 'listings#index'
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_and_belongs_to_many :saved_listings, class_name: 'Listing', join_table: 'listings_users'
  has_many :listings, foreign_key: :tutor_id, dependent: :destroy

  has_many :bookings_as_student, foreign_key: :student_id, class_name: 'Booking', dependent: :destroy
  has_many :bookings_as_tutor, through: :listings, source: :bookings

  has_many :made_reviews, foreign_key: :student_id, class_name: 'Review'
  has_many :reviews, foreign_key: :tutor_id, class_name: 'Review', dependent: :destroy

  has_one_attached :profile_picture

  before_destroy :remove_review_student_id, prepend: true

  validates :name, presence: true, length: { minimum: 3 }

  # returns boolean true if a user has a booking with the tutor
  def booking_with?(tutor)
    tutor.bookings_as_tutor.where(student: self).exists?
  end

  # returns boolean true if a tutor has already been revied by the current user.
  def reviewed?(tutor)
    tutor.reviews.where(student: self).exists?
  end

  # Removes the student_id foreign key from the review record in the review table
  def remove_review_student_id
    made_reviews.update_all(student_id: nil)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # Renders the show User view based on the user id
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/show.html.erb
<section>
  <div class="container mt-5 mb-5">
    <div class="row d-flex justify-content-center">
      <div class="col-md-7">
        <div class="card p-3 py-4">
          <div class="text-center">
            <% if @user.profile_picture.attached? %>
              <%= cl_image_tag @user.profile_picture.key, crop: :scale, width: 150, cloud_name: 'dakvf2jcu' %>
            <% else %>
              <svg xmlns="http://www.w3.org/2000/svg" aria-hidden="true" role="img" width="150" height="auto" preserveAspectRatio="xMidYMid meet" viewBox="0 0 24 24"><path fill="currentColor" d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10s10-4.48 10-10S17.52 2 12 2zm0 4c1.93 0 3.5 1.57 3.5 3.5S13.93 13 12 13s-3.5-1.57-3.5-3.5S10.07 6 12 6zm0 14c-2.03 0-4.43-.82-6.14-2.88a9.947 9.947 0 0 1 12.28 0C16.43 19.18 14.03 20 12 20z"/></svg>
            <% end %>
          </div>
          <div class="text-center mt-3">
            <h5 class="mt-2 mb-0"><%= @user.name %></h5>
            <% @user.roles.each_with_index do |role, index| %>
              <span><%= role.name.capitalize %><% if index != @user.roles.count - 1 %>,<% end %>
              </span>
            <% end %>
            <div class="px-4 mt-1">
              <p class="fonts"> <%= @user.bio %> </p>
            </div>
            <div class="buttons">
              <% if current_user.reviewed?(@user) && current_user != @user && current_user.reviewed?(@user) && current_user %>
                <%= button_to('Edit Review', edit_review_path(current_user.made_reviews.find_by(tutor: @user).id), class: 'btn btn-primary', method: :get)%>
              <% elsif current_user && current_user != @user && current_user.booking_with?(@user)%>
                <%= link_to 'Make Review', new_user_review_path(@user.id), class: 'btn btn-primary px-4 ms-3' %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<% if @user.reviews.first.present?%>
  <section class="container-fluid mb-5">
    <div class="row justify-content-center">
      <div class="col-7">
        <h2 class="inline-block"> <%= @user.name%>'s reviews </h2>
        <div class="accordion" id="accordionExample">
          <% @user.reviews.order(created_at: :desc).each do |review| %>
            <div class="accordion-item">
              <h2 class="accordion-header" id="heading<%= review.id %>">
                <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapse<%= review.id %>" aria-expanded="true" aria-controls="collapse<%= review.id %>">
                  <%= review.rating%> / 5 by <%= review.student.name %> <cite title="Source Title"> (student <%= review.updated_at %>) </cite>
                </button>
              </h2>
              <div id="collapse<%= review.id %>" class="accordion-collapse collapse" aria-labelledby="heading<%= review.id %>" data-bs-parent="#accordionExample">
                <div class="accordion-body">
                  <%= review.content %>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </section>
<% end %>
<section class="container mb-5">
  <div class="row">
    <h2 class="inline-block"> <%= @user.name%>'s Listings: </h2>
    <% @user.listings.each do |listing| %>
      <div class="col-12 col-md-4 col-lg-3 py-2">
        <div class="card border-0">
          <div class="card-body d-flex flex-column align-items-center">
            <h5 class="card-title pt-3"> <%= listing.title %></h5>
            <p class="card-text text-center"> <%= truncate(listing.content, length: 125, omission: '...') %></p>
            <%= button_to('Show Listing', listing, class: 'btn btn-primary', method: :get) %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</section>