config/routes.rb
Rails.application.routes.draw do
  resources :watchlist, only: %i[index create destroy]

  devise_for :users, controllers: { registrations: 'registrations' }

  resources :reviews, except: %i[show new create]

  resources :users, only: %i[show] do
    resources :reviews, only: %i[create new]
  end

  resources :bookings, except: %i[new create show]

  # Defines the resourceful routes for the listings controller
  resources :listings do
    resources :bookings, only: %i[new create]
  end

  # Defines the root path route ("/")
  root 'listings#index'
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: %i[edit update destroy]
  before_action :review_params, only: %i[create update]
  before_action :authenticate_user!
  before_action :check_auth

   # Sets a list of made_reviews and renders the review index view.
  def index
    @reviews = current_user.made_reviews.order(created_at: :desc)
  end 
  # Creates and sets a new instance of review.
  def new
    @review = Review.new
    @user = User.find(params[:user_id])
  end

  def create
    @review = Review.new(student: current_user, tutor_id: params[:user_id], **review_params)
    create_validator(@review, @review.tutor)
  end
  # Renders the edit Review form
  def edit
    if (current_user != @review.student) || (current_user.present? == false)
      flash[:notice] = 'Access Denied'
      return redirect_to(:root)
    end
  end
  # Attempts to update the review and if it passes validation it will render the @review.tutor
  # else, it will redirect to root_path with relevent error alert
  def update
    if (current_user != @review.student) || (current_user.present? == false)
      flash[:notice] = 'Access Denied'
      return redirect_to(:root)
    end
    update_validator(@review, review_params, @review.tutor)
  end

  # Destroys the review record
  def destroy
    @review.destroy
    redirect_to reviews_path
  end

  private
  def check_auth
    authorize Review
  end

  def review_params
    params.require(:review).permit(:content, :rating)
  end

  def set_review
    @review = Review.find(params[:id])
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_form.html.erb
  <fieldset class="mb-3 d-flex flex-column col-12 col-md-4">
    <%= f.label "Rating" %>
    <%= f.number_field :rating, in: 1...6, step: 1 %>
  </fieldset>
  <fieldset class="mb-3 d-flex flex-column col-12 col-md-4">
    <%= f.label "Content" %>
    <%= f.text_area :content %>
  </fieldset>
  <fieldset>
    <%= f.submit class: 'btn btn-primary' %>
  </fieldset>

app/views/reviews/edit.html.erb
<section class="m-3">
  <div class="container">
    <div class="row justify-content-center">
      <div  class="col-md-3">
      </div>
      <div  class="col-6">
        <h5 class="d-inline-block">Edit Review:</h5>
      </div>
    </div>
    <div class="row justify-content-center">
      <div  class="col-md-3">
      </div>
      <div class="col-6">
        <%= form_with(model: @review, data: {turbo: false}, method: 'put') do |f| %>
          <%= render partial: 'form', locals: { f: f } %>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/reviews/index.html.erb
<div class="container mt-5">
  <div class="row justify-content-center">
    <div  class="col-6 text-center p-5">
      <h1 class="d-inline-block">Made Reviews:</h1>
    </div>
  </div>
  <div class="row d-flex justify-content-center">
    <div class="col-md-7">
      <div class="card p-3 py-4">
        <div class="text-center">
        <% if @reviews.empty? %>
        <div class="card text-center">
        <div class="card-header">
        <h2>Someone knows their routes 👍 / you have made no reviews</h2>
        </div>
        </div>
        <% end %>
          <% @reviews.each do |review| %>
            <div class="card text-center">
              <div class="card-header">
                <%= review.tutor.name %> <%= review.rating %>/5
              </div>
              <div class="card-body">
                <p class="card-text"> <%= review.content%> </p>
              </div>
              <div class="card-footer text-muted">
                <span> last updated: <%= review.updated_at  %> </span>
              </div>
            </div>
            <div  class="col-12 col-md-2 d-flex justify-content-md-between">
              <%= button_to('Edit', edit_review_path(review.id), class: 'btn btn-warning', method: :get)%>
              <%= button_to('Delete', review_path(review.id), class: 'btn btn-danger mb-4', method: :delete, form: { data: { turbo_confirm: "Are you sure you want to delete your review? " } }) %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/reviews/new.html.erb
<section class="m-3">
  <div class="container">
    <div class="row justify-content-center">
      <div  class="col-md-3">
      </div>
      <div  class="col-6">
        <h5 class="d-inline-block">New Review: </h5>
      </div>
    </div>
    <div class="row justify-content-center">
      <div  class="col-md-3">
      </div>
      <div class="col-6">
        <%= form_with(model: @review, url: [@user, @review], data: {turbo: false}, method: 'post') do |f| %>
          <%= render partial: 'form', locals: { f: f } %>
        <% end %>
      </div>
    </div>
  </div>
</section>